[project]
name = 'Entanglement-Communication-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.entangled-pair-management]
path = 'contracts/entangled-pair-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.message-encoding]
path = 'contracts/message-encoding.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
